--- 
title: Análisis multitemporal de la cobertura vegetal en el Parque Nacional Bahuaja
  Sonene
author: "Herrera Fernando, Gonzales Karen"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
documentclass: book
---

# Introducción
La pérdida de la cobertura vegetal causada por las actividades antrópicas afecta directamente al clima, flora, fauna, suelo del lugar afectado. En el Parque Nacional Bahuaja Sonene; la perdida de cobertura vegetal es originado principalmente por actividades como la minera ilegal, deforestación para construír laboratorios del narcotráfico así como expansión de la frontera agrícola.
En el presente trabajo usamos las técnicas de teledetección para calcular cuantitativamente el cambio y la pérdida de cobertura vegetal, se usa principalmente las imágenes de las misiones Landsat-5 y Landsat-8. Se realizó la clasificación tomando tres (3) clases (_forest, damaged_forest, water), añadido a esto se procedió a usar el algoritmo Random Forest (RF) dentro del servicio para editar códigos de Google Earth Engine (GEE). 
 
# Metodología
En este estudio utilizamos imágenes de las misiones Landsat, cabe mencionar que utilizamos las imágenes de Level 1-C que son las que tienen el pre-procesamiento correctamente realizado para el trabajo que nos compete. Añadido a esto utilizamos el algoritmo Random Forest que nos permite realizar la clasificación supervisada de las clases:
-Forest
-Damaged Forest
-Water
El proceso de clasificación supervisada fue realizado integramente en el code editor de Google Earth Engine (GEE), esta plataforma nos permite realizar todas las operaciones de una manera fácil y rápida, sin consumir recursos de nuestros ordenadores ya que todo el procesamiento es en la nube.
Dentro de GEE, se elaboró el code para este proyecto (JavaScript) y posterior a esto se procedió a realizar la selección de puntos de entrenamiento (training points); luego a esto pudimos correr el algoritmo RF.
Para evitar el sesgo y alcanzar la precisión requerida en este tipo de trabajos se realizó la matriz de confusión y los índices correspondientes (Producer y Kappa).

# Marco teórico 


# Resultados


# Conclusiones


# Bibliografía


# Anexos

